import { BACKUP_FORMAT_VERSION, backupStateIntegrity } from './src_core_backup.js';
import { APP_VERSION } from './src_core_schema.js';
import { validateCurrentStateAllowingNavigationRepair } from './src_core_migrations.js';

const CURRENT_COLLECTIONS = Object.freeze([
  'itinerary','routePoints','expenses','reservations','calendarEvents','journeyHistory',
  'checklists','vault','attachments','accounts','alerts','streaming','protectedEmails'
]);
const LEGACY_CORE_COLLECTIONS = Object.freeze(['itinerary','expenses','reservations','calendarEvents','checklists','vault']);

const V2_META_FIELDS = Object.freeze(['createdAt','modifiedAt','revision','appVersion']);
const V2_SETTINGS_FIELDS = Object.freeze([
  'journeyStartDate','dateFormat','defaultTravellers','defaultCurrency','annualBudgetAUD','pinEnabled','schengen'
]);
const V2_SCHENGEN_FIELDS = Object.freeze([
  'status','daysUsed','daysRemaining','entryDate','plannedExitDate','mustLeaveByDate','lastCheckedDate','note'
]);
const STRICT_SETTINGS_FIELDS = Object.freeze([...V2_SETTINGS_FIELDS,'pinHash','pinRecoveryNotice']);
const MIN_SUPPORTED_V2_GENERATION = 35;
const STRICT_PERSISTED_GENERATION_MIN = 41;


function appGeneration(value) {
  // Persisted runtime identities use a numeric app version followed by the
  // continuity generation (for example 1.2.0-v36-recovery or
  // 1.2.0-v42-active-continuity). Do not salvage a generation number from an
  // arbitrary/corrupted string merely because it happens to contain "v40".
  const text = typeof value === 'string' ? value.trim() : '';
  const match = text.match(/^\d+(?:\.\d+){1,3}-v(\d+)(?:-[a-z0-9][a-z0-9._-]*)?$/i);
  return match ? Number(match[1]) : null;
}

function assertBackupAppVersionCompatible(value) {
  const backupVersion = String(value || '').trim();
  if (!backupVersion) throw new Error('Backup app version is missing');
  if (backupVersion === APP_VERSION) return;
  const backupGeneration = appGeneration(backupVersion);
  const currentGeneration = appGeneration(APP_VERSION);
  if (Number.isInteger(backupGeneration) && Number.isInteger(currentGeneration) && backupGeneration <= currentGeneration) return;
  if (Number.isInteger(backupGeneration) && Number.isInteger(currentGeneration) && backupGeneration > currentGeneration) {
    throw new Error(`Backup was created by a newer app generation (V${backupGeneration}); this app supports up to V${currentGeneration}`);
  }
  throw new Error('Backup app version is not compatible with this app');
}

function hasOwn(object, key) {
  return Object.prototype.hasOwnProperty.call(object, key);
}

function assertFields(object, fields, label) {
  const missing = fields.filter(key => !hasOwn(object, key));
  if (missing.length) throw new Error(`Backup is incomplete: missing ${label} ${missing.join(', ')}`);
}

function isPlainObject(value) {
  return value != null && typeof value === 'object' && !Array.isArray(value);
}

function assertRecognisableBackupState(state, { strictKnownBackup = false } = {}) {
  if (!isPlainObject(state)) throw new Error('Backup state must be an object');

  const rawVersion = state.schemaVersion;
  const numericVersion = rawVersion == null || rawVersion === '' ? 0 : Number(rawVersion);
  const currentShape = numericVersion === 2;

  if (currentShape) {
    if (!isPlainObject(state.meta) || !isPlainObject(state.settings) || !isPlainObject(state.ui)) {
      throw new Error('Backup is incomplete: current app metadata, settings or UI state is missing');
    }
    const v2Generation = appGeneration(state.meta.appVersion);
    if (!Number.isInteger(v2Generation) || v2Generation < MIN_SUPPORTED_V2_GENERATION) {
      throw new Error('Backup schema V2 app generation is missing or predates the supported continuity line');
    }
    const missing = CURRENT_COLLECTIONS.filter(key => !Array.isArray(state[key]));
    if (missing.length) throw new Error(`Backup is incomplete: missing ${missing.join(', ')}`);

    // Schema V2 has been used across several compatible app generations. Keep
    // older V2 backups migratable, but never let a grossly truncated V2 object
    // be default-filled into plausible current data and overwrite a good app.
    assertFields(state.meta, V2_META_FIELDS, 'metadata fields:');
    assertFields(state.settings, V2_SETTINGS_FIELDS, 'settings fields:');
    if (!isPlainObject(state.settings.schengen)) throw new Error('Backup is incomplete: Schengen settings are missing');
    assertFields(state.settings.schengen, V2_SCHENGEN_FIELDS, 'Schengen fields:');
    // UI/navigation fields are non-authoritative and safe to reconstruct. The
    // UI object is still mandatory, but missing/stale fields are repaired by
    // migration instead of rejecting an otherwise-valid travel backup.

    // Versioned backups are generated by this runtime, so they must contain the
    // complete current persisted shape. Missing fields indicate truncation, not
    // a legacy format that migration is allowed to invent defaults for.
    if (strictKnownBackup) {
      assertFields(state.settings, STRICT_SETTINGS_FIELDS, 'settings fields:');
    }
    return;
  }

  // Older supported backups may legitimately lack later collections, but they
  // still need to look like Travel Command Centre data before migration is
  // allowed to fill compatibility defaults. This prevents arbitrary/truncated
  // JSON objects from being normalised into an empty app and replacing good data.
  if (!isPlainObject(state.meta) && !isPlainObject(state.settings) && rawVersion == null) {
    throw new Error('Backup state is not recognisable as Travel Command Centre data');
  }
  const coreCount = LEGACY_CORE_COLLECTIONS.filter(key => Array.isArray(state[key])).length;
  if (coreCount < 4) throw new Error('Backup is incomplete: too much core travel data is missing');
}

export function parseBackupPayload(serialized) {
  const payload = JSON.parse(serialized);
  if (payload?.format !== 'TravelCommandCentreBackup') throw new Error('Invalid backup format');
  if (!payload.state) throw new Error('Backup contains no state');

  const versioned = payload.backupVersion != null;
  const hasModernWrapperMarker = hasOwn(payload, 'appVersion') || hasOwn(payload, 'integrity');
  if (!versioned && hasModernWrapperMarker) throw new Error('Backup version information is missing or incomplete');
  const embeddedGeneration = appGeneration(payload.state?.meta?.appVersion);
  if (!versioned && Number(payload.state?.schemaVersion) === 2 && Number.isInteger(embeddedGeneration) && embeddedGeneration >= STRICT_PERSISTED_GENERATION_MIN) {
    throw new Error('Current-generation backup is missing its required version and integrity envelope');
  }
  if (versioned && payload.backupVersion !== BACKUP_FORMAT_VERSION) throw new Error('Unsupported backup format version');
  if (versioned) {
    assertBackupAppVersionCompatible(payload.appVersion);
    if (payload.appVersion !== payload.state?.meta?.appVersion) throw new Error('Backup app version does not match its state');
    if (!isPlainObject(payload.integrity) || payload.integrity.algorithm !== 'fnv1a32-utf16le' || !Number.isInteger(payload.integrity.length) || !/^[a-f0-9]{8}$/.test(String(payload.integrity.checksum || ''))) {
      throw new Error('Backup integrity information is missing or invalid');
    }
    const actualIntegrity = backupStateIntegrity(payload.state);
    if (actualIntegrity.length !== payload.integrity.length || actualIntegrity.checksum !== payload.integrity.checksum) {
      throw new Error('Backup integrity check failed; the file may be incomplete or altered');
    }
  }

  if (versioned) {
    for (const attachment of payload.state.attachments || []) {
      if (typeof attachment?.dataUrl !== 'string' || !attachment.dataUrl) {
        throw new Error('Backup is incomplete: Vault screenshot payload bytes are missing');
      }
      if (Object.prototype.hasOwnProperty.call(attachment, 'assetKey')) {
        throw new Error('Backup contains an internal-only Vault screenshot storage reference');
      }
    }
  }

  const backupGeneration=versioned?appGeneration(payload.appVersion):null;
  const currentGeneration=appGeneration(APP_VERSION);
  const strictKnownBackup=versioned&&Number.isInteger(backupGeneration)&&Number.isInteger(currentGeneration)&&backupGeneration>=STRICT_PERSISTED_GENERATION_MIN&&backupGeneration<=currentGeneration;
  assertRecognisableBackupState(payload.state, { strictKnownBackup });
  // Every backup from the strict V41+ continuity generations must already be
  // complete and canonical before migration/defaulting is allowed. Older checksum-valid
  // generations may use the explicit migration path after wrapper integrity
  // and the known minimum V2 shape have been verified.
  if (strictKnownBackup) validateCurrentStateAllowingNavigationRepair(payload.state, { now:payload.state?.meta?.modifiedAt || new Date().toISOString() });
  return payload.state;
}

export function restoreBackup(stateService, serialized) {
  const nextState = parseBackupPayload(serialized);
  if (stateService?.vaultAssetStore && typeof stateService.replaceValidatedWithVaultAssets === 'function') {
    return stateService.replaceValidatedWithVaultAssets(nextState);
  }
  return stateService.replaceValidated(nextState);
}
